[package]
name = "sift"
version = "0.1.0"
edition = "2021"

[dependencies]
ratatui = "0.29"
crossterm = "0.28"
ansi-to-tui = "7"
unicode-width = "0.2"
anyhow = "1"
serde = { version = "1.0.229", features = ["derive"] }
toml = "1.1.3"
image = { version = "0.25", default-features = false, features = ["png","jpeg","gif","bmp","webp"] }
base64 = "0.22"
jpeg-decoder = "0.3.2"

[profile.release]
opt-level = "z"     # 以体积为优化目标
lto = "fat"         # 全量链接时优化，跨 crate 内联/裁剪
codegen-units = 1   # 单代码生成单元，利于体积优化
panic = "abort"     # 不生成 unwind 表
strip = true        # 去除符号与调试信息
